#!/bin/sh
# Xephyr :1 -screen 500x300 &
name="diagram-test-app"
dest="dist/build/$name"
if [ ! -d $dest ]; then
    mkdir $dest
fi
ps aux | grep "[d]ist/build/$name" | awk '{print $2}' | xargs kill
ghc --make -isrc -outputdir $dest/$name-tmp tests/DiagramTestApp.hs -o $dest/$name &&
(DISPLAY=:1 ./$dest/$name &)
