#!/bin/sh
# Xephyr :1 -screen 500x300 > /dev/null 2>&1 &
name="DiagramTestApp"
dest="dist/build/$name"
export DISPLAY=:1
mkdir -p $dest
ps aux | grep "[d]ist/build/$name" | awk '{print $2}' | xargs kill
ghc --make -isrc -outputdir $dest/$name-tmp tests/$name.hs -o $dest/$name &&
(./$dest/$name &)
